### ISSUE TITLE
Add your latest code and code should not break untill unless i say Bye.

### ISSUE THREAD

**Issue by sidhanta1989** [vinotharumugam1993/ChatBot_V_1.0#2]

**Comment by nknarendra7** [comment]
`

"""

@author: narendra
"""

from chatterbot.trainers import ListTrainer,ChatterBotCorpusTrainer
from chatterbot import ChatBot
import os,time
from gtts import gTTS
import speech_recognition as sr
from pygame import mixer

path = r'/Users/narendrakumar/Library/Preferences/PyCharmCE2019.1/scratches/Chatterbot_corpus/chatterbot-corpus-master/chatterbot_corpus/data/english/'

r = sr.Recognizer()
bot = ChatBot('Bot')
trainer = ChatterBotCorpusTrainer(bot)

for files in os.listdir(path):
    trainer.train(path + files)

while True:
    with sr.Microphone() as source:
        print("Say something!")
        r.adjust_for_ambient_noise(source)
        audio = r.listen(source)
    try:
        print("Google Speech Recognition thinks you said:" + r.recognize_google(audio))
    except sr.UnknownValueError:
        print("Google Speech Recognition could not understand audio")
        time.sleep(4)
        continue
    except sr.RequestError as e:
        print("Could not request results from Google Speech Recognition service; {0}".format(e))

    except LookupError:  # speech is unintelligible
        print("Could not understand audio")
        time.sleep(4)
        continue
    # except sr.WaitTimeoutError as e:
    #     print("Sorry i am not programed to be on stand by mode!!")
    #     break


    message = str(r.recognize_google(audio))

    if message.strip() != 'Bye':
        reply = bot.get_response(message)
        mytext = str(reply)
        language = 'en'
        myobj = gTTS(text=mytext, lang=language, slow=False)
        myobj.save("welcome.mp3")

        mixer.init()
        mixer.music.load('welcome.mp3')
        mixer.music.play()
        print('Desi_Thanos:', reply)
        time.sleep(5)

    if message.strip() == 'Bye' or message.strip() == 'bye':
        print('Desi_Thanos:Bye')
        break



`

**Comment by nknarendra7** [comment]
Please try to run it and check the output. I did corrections.
